typography_spectrum: 0.07131
content_rating:
  adult: false
color:
  lightness: 0
  brandColors:
    - '#000000'
    - '#a2a7ac'
    - '#435873'
    - '#b2671a'
    - '#fc9d21'
  saturation: 0.75
  brandStrength: 0.797619
  rhythmicContrast: 0.25
github: true
opengraph: {}
layout_spectrum: 1
analytics: {}
author:
  name: Christopher Reign DeRenzo
  url: 'http://reign-tech.com'
  email: reigntech@gmail.com
name: reign-tech
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Engineering
    id: a6df4c0e-9184-4133-bc81-e1cdcd787f27
    type: content
  - name: EE
    id: f5337470-a1cf-4773-9ab1-8e797a2d9c3d
    type: content
  - name: EE
    id: 4b154908-a456-46c8-860b-68104412615a
    type: content
  - name: JavaFX
    id: 41e991f6-8c83-444c-b20c-1a835eada2be
    type: content
  - name: iOS
    id: cf5942ce-f980-4a3e-8976-850bb24ec6d7
    type: content
  - name: Mechanics
    id: f45e57fd-6644-4b05-9d0e-1e20c057199f
    type: content
  - name: Sumpin New
    id: a9ff66e9-3421-4da3-a7aa-7d5e04ee685e
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Reign-Tech
content: []
description: >-
  Technologist in the field of software and hardware for interacting with the
  environment.
purpose: []
