typography_spectrum: 0.07131
color:
  brandColors:
    - '#000000'
    - '#a2a7ac'
    - '#435873'
    - '#b2671a'
    - '#fc9d21'
  brandStrength: 0.797619
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: reign-tech
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Wireless Thermostat
    id: f5337470-a1cf-4773-9ab1-8e797a2d9c3d
    type: content
  - name: JavaFX
    id: 41e991f6-8c83-444c-b20c-1a835eada2be
    type: content
  - name: Mechanics
    id: f45e57fd-6644-4b05-9d0e-1e20c057199f
    type: content
  - name: iOS
    id: cf5942ce-f980-4a3e-8976-850bb24ec6d7
    type: content
  - name: Electro-Mechanical
    id: 4b154908-a456-46c8-860b-68104412615a
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Reign-Tech
description: >-
  Technologist in the field of software and hardware for interacting with the
  environment.
purpose: []
