typography_spectrum: 0.07131
color:
  brandColors:
    - '#000000'
    - '#a2a7ac'
    - '#435873'
    - '#b2671a'
    - '#fc9d21'
  brandStrength: 0.797619
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: reign-tech
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Reign-Tech
description: >-
  Technologist in the field of software and hardware for interacting with the
  environment.
purpose: []
