name: reign-tech
favicon: null
layout_spectrum: 0.26549
typography_spectrum: 0.07131
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a2a7ac'
    - '#435873'
    - '#b2671a'
    - '#fc9d21'
  brandStrength: 0.797619
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
